import { writeFileSync } from "node:fs";
import datasetJson from "../data/dataset.json";
import type { Dataset } from "../lib/engine/types";
import { STRINGS, type Str } from "../lib/i18n/strings";

const ds = datasetJson as unknown as Dataset;
const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const lines: string[] = [
  "# Malayalam strings for native-speaker review",
  "",
  "Generated by `npm run i18n:review`. Nothing here was produced by a runtime AI model. UI strings live in `lib/i18n/strings.ts`; dataset strings live in `dataset/anavandi-dataset.xlsx`.",
  "",
  "Mark a UI string as checked by adding `mlReviewed: true` to it in `strings.ts`. Fix dataset strings in the workbook and run `npm run data`.",
  "",
  "## Interface strings",
  "",
  "| Key | English | Malayalam | Status | Note |",
  "|---|---|---|---|---|",
];
for (const [k, v] of Object.entries(STRINGS) as [string, Str][]) {
  lines.push(`| ${k} | ${esc(v.en)} | ${esc(v.ml)} | ${v.mlReviewed ? "reviewed" : "NOT REVIEWED"} | ${esc(v.mlNote ?? "")} |`);
}
lines.push("", "## Dataset strings", "", "| Where | English | Malayalam |", "|---|---|---|");
const add = (where: string, en?: string, ml?: string) => en && lines.push(`| ${where} | ${esc(en)} | ${esc(ml || "MISSING")} |`);
for (const s of ds.schemes) {
  add(`scheme ${s.id} name`, s.name.en, s.name.ml);
  add(`scheme ${s.id} summary`, s.summary.en, s.summary.ml);
  add(`scheme ${s.id} authority`, s.authority.en, s.authority.ml);
}
for (const f of ds.facts) {
  add(`fact ${f.id} label`, f.label.en, f.label.ml);
  add(`fact ${f.id} question`, f.question.en, f.question.ml);
  for (const o of f.options) add(`option ${f.id}.${o.value}`, o.label.en, o.label.ml);
}
for (const d of ds.documents) add(`document ${d.id}`, d.name.en, d.name.ml);
for (const t of ds.locationTypes) add(`office type ${t.id}`, t.label.en, t.label.ml);
for (const [k, v] of Object.entries(ds.disclaimer)) add(`disclaimer ${k}`, v.en, v.ml);
writeFileSync("docs/malayalam-review.md", lines.join("\n") + "\n");
console.log(`Wrote docs/malayalam-review.md (${lines.length} lines)`);
