import { existsSync, readFileSync, writeFileSync } from "node:fs";
import datasetJson from "../data/dataset.json";
import { auditDataset, type AuditFlag } from "../lib/assist/audit";
import { assistConfigured, assistModel, complete } from "../lib/assist/model";
import { leavesOf } from "../lib/engine/evaluate";
import type { Dataset, Leaf, Scheme } from "../lib/engine/types";
import { conditionText } from "../lib/i18n/describe";

const ds = datasetJson as unknown as Dataset;
const args = process.argv.slice(2);
const check = args.includes("--check");
const useLlm = args.includes("--llm");
const limitArg = args.find((a) => a.startsWith("--limit="));
const limit = limitArg ? Number(limitArg.split("=")[1]) : Infinity;
const out = "docs/rule-audit.md";

const sourceTexts: Record<string, string> = {};
for (const s of ds.sources) {
  if (s.localFile?.endsWith(".txt") && existsSync(s.localFile)) sourceTexts[s.id] = readFileSync(s.localFile, "utf8");
}

const report = auditDataset(ds, sourceTexts);
const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

interface Opinion {
  schemeId: string;
  leafId: string;
  verdict: string;
  reason: string;
}

async function secondOpinions(): Promise<Opinion[]> {
  const jobs: { scheme: Scheme; leaf: Leaf }[] = [];
  for (const scheme of ds.schemes) for (const leaf of leavesOf(scheme.rule)) if (leaf.source?.quote) jobs.push({ scheme, leaf });
  const picked = jobs.slice(0, limit);
  const system = [
    "You check whether an encoded eligibility condition matches an official Kerala Government quotation.",
    "Judge only the quotation you are given. Pay attention to the direction of limits: below versus not more than, at least versus more than.",
    'Reply with JSON only: {"verdict":"supports"|"unclear"|"contradicts","reason":"under 20 words"}',
  ].join("\n");
  const results: Opinion[] = [];
  let next = 0;
  async function worker() {
    while (next < picked.length) {
      const { scheme, leaf } = picked[next++];
      const fact = ds.facts.find((f) => f.id === leaf.fact);
      const user = [
        `Scheme: ${scheme.name.en}`,
        `Encoded condition: ${conditionText(leaf, fact, "en")} (fact=${leaf.fact}, op=${leaf.op}, value=${JSON.stringify(leaf.value)})`,
        `Quotation: ${leaf.source!.quote}`,
      ].join("\n");
      try {
        const text = await complete(system, user, { maxTokens: 120, timeoutMs: 20000 });
        const json = JSON.parse(text.replace(/```json|```/g, "").trim()) as { verdict?: string; reason?: string };
        results.push({ schemeId: scheme.id, leafId: leaf.id, verdict: String(json.verdict ?? "unclear"), reason: String(json.reason ?? "") });
      } catch {
        results.push({ schemeId: scheme.id, leafId: leaf.id, verdict: "error", reason: "no usable reply" });
      }
    }
  }
  await Promise.all(Array.from({ length: 4 }, worker));
  return results.sort((a, b) => (a.schemeId + a.leafId).localeCompare(b.schemeId + b.leafId));
}

async function main() {
  let opinions: Opinion[] = [];
  if (useLlm) {
    if (!assistConfigured()) {
      console.error("--llm needs ANTHROPIC_API_KEY in the shell. Running deterministic checks only.");
    } else {
      opinions = await secondOpinions();
    }
  }

  const errors = report.flags.filter((f) => f.level === "error");
  const warns = report.flags.filter((f) => f.level === "warn");
  const row = (f: AuditFlag) => `| ${f.level} | ${f.schemeId} | ${esc(f.ref)} | ${f.check} | ${esc(f.detail)} |`;
  const lines = [
    "# Rule audit",
    "",
    "Generated by `npm run audit:rules`. Deterministic checks run on every build in CI. The AI second opinion is advisory: it never edits the dataset, and a person decides every change in the workbook.",
    "",
    `Dataset built ${ds.meta.generatedAt}. ${report.schemes} schemes, ${report.leaves} conditions (${report.numericLeaves} numeric thresholds). Conditions awaiting a second human review: ${report.pendingReview}.`,
    "",
    "## Checks",
    "",
    "- every condition has a source that exists and a quotation",
    "- every numeric threshold appears in its quotation (digits, Indian grouping, lakh, English or Malayalam number words)",
    "- limit direction cues in the quotation (at least / below / not more than) agree with the operator",
    "- quotations from stored text sources appear verbatim in that text",
    "- every document and office type referenced by a scheme is defined",
    "",
    `## Findings: ${errors.length} errors, ${warns.length} warnings`,
    "",
  ];
  if (report.flags.length === 0) lines.push("No findings.");
  else lines.push("| Level | Scheme | Ref | Check | Detail |", "|---|---|---|---|---|", ...[...errors, ...warns].map(row));
  if (opinions.length) {
    const counts = opinions.reduce<Record<string, number>>((m, o) => ((m[o.verdict] = (m[o.verdict] ?? 0) + 1), m), {});
    lines.push(
      "",
      `## AI second opinion (advisory, ${assistModel()})`,
      "",
      `Checked ${opinions.length} conditions: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(", ")}. Only non-supporting verdicts are listed.`,
      "",
      "| Scheme | Condition | Verdict | Reason |",
      "|---|---|---|---|",
      ...opinions.filter((o) => o.verdict !== "supports").map((o) => `| ${o.schemeId} | ${o.leafId} | ${o.verdict} | ${esc(o.reason)} |`),
    );
  }
  writeFileSync(out, lines.join("\n") + "\n");
  console.log(`Wrote ${out}: ${errors.length} errors, ${warns.length} warnings${opinions.length ? `, ${opinions.length} AI opinions` : ""}`);
  if (check && errors.length) process.exit(1);
}

main();
